package org.jboss.xavier.analytics.rules.workload.inventory;

import org.jboss.xavier.analytics.pojo.input.workload.inventory.VMWorkloadInventoryModel
import org.jboss.xavier.analytics.pojo.output.workload.inventory.WorkloadInventoryReportModel
import java.util.HashSet;

dialect "java"
agenda-group "Flags"
auto-focus true

rule "Flags"
    when
        vmWorkloadInventoryModel : VMWorkloadInventoryModel(
            nicsCount != null,
            hasRdmDisk != null
            //vmDiskFilenames != null
        )
        workloadInventoryReport : WorkloadInventoryReportModel()
    then
        HashSet flags = new HashSet<>();

        if (vmWorkloadInventoryModel.getNicsCount()>4)
        {
            flags.add(WorkloadInventoryReportModel.MORE_THAN_4_NICS_FLAG_NAME);
        }
        if (vmWorkloadInventoryModel.isHasRdmDisk())
        {
            flags.add(WorkloadInventoryReportModel.RDM_DISK_FLAG_NAME);
        }

        //TODO Add Shared Disk check to the rule here

        modify(workloadInventoryReport)
        {
            setFlagsIMS(flags)
        }

        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Flags").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Targets").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Complexity").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Workloads").setFocus();
end
