package org.jboss.xavier.analytics.rules.workload.inventory;

import org.jboss.xavier.analytics.pojo.input.workload.inventory.VMWorkloadInventoryModel
import org.jboss.xavier.analytics.pojo.output.workload.inventory.WorkloadInventoryReportModel
import java.util.HashSet;

dialect "java"
agenda-group "Complexity"
lock-on-active true
auto-focus false

function boolean osDescriptionContainsString(String osDescription, String match)
{
    return osDescription.toLowerCase().contains(match.toLowerCase());
}

rule "RHEL_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "Red Hat Enterprise Linux")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("RHEL")
        }
end

rule "SUSE_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "SUSE")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("SUSE")
        }
end

rule "Windows_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "Windows")
        )
    then
        String osFamily = "Windows Other";
        if (osDescriptionContainsString(workloadInventoryReport.getOsDescription(), "Windows Server"))
        {
            osFamily = "Windows Server";
        }

        modify(workloadInventoryReport)
        {
            setOsFamily(osFamily)
        }
end

rule "OracleLinux_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "Oracle Linux")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("Oracle Linux")
        }
end

rule "Centos_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "CentOS")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("CentOS")
        }
end

rule "Ubuntu_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "Ubuntu")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("Ubuntu")
        }
end

rule "Debian_OSFamily"
    when
        workloadInventoryReport : WorkloadInventoryReportModel(
            osDescription != null,
            osDescriptionContainsString(osDescription, "Debian")
        )
    then
        modify(workloadInventoryReport)
        {
            setOsFamily("Debian")
        }
end
